### ISSUE TITLE
Items per row is not there 

### ISSUE THREAD

**Issue by AKBEHERA793** [jmir1/aniyomi-mpv-beta#101]
I personally prefer 3 items per row and it's bugging me since it's not there and it feels annoying to see big and 2 items a row

**Comment by fakebhai** [comment]
is grid size filter isn't working for you?

**Comment by fakebhai** [comment]
![Screenshot_2023_0807_161255.jpg](https://github.com/jmir1/aniyomi-mpv-beta/assets/101493467/ec3f9438-e825-4028-b6f3-f6a4e6553186)
are you talking about this?

**Comment by AKBEHERA793** [comment]
I don't know how did you do that ,,  there are no options here like that
