### ISSUE TITLE
Cannot bypass cloud fare 

### ISSUE THREAD

**Issue by AKBEHERA793** [jmir1/aniyomi-mpv-beta#102]
Some extensions like unique stream and toongod cannot bypass cloudfare ,,, am I supposed to something in settings or is it a bug

**Comment by fakebhai** [comment]
stop creating issues for everything. if you're unaware how to diagnose common issues check their troubleshooting on website or ask for help on discord.

**Comment by AKBEHERA793** [comment]
Sorry bro
