### ISSUE TITLE
Aniyomi extension Aniwatch is not working

### ISSUE THREAD

**Issue by Curiousnewbie** [jmir1/aniyomi-mpv-beta#108]
Aniwatch extension is not working for past a week. It changed it basic url to aniwatchtv.com. if you add any option to override base url by the user then it would be better to update everytime it changes the url. Can you pls look into this matter?

**Comment by Mahmoud-Elseidi** [comment]
replace it with hianime

**Comment by Mahmoud-Elseidi** [comment]
is the same thing but with another name

**Comment by Curiousnewbie** [comment]
Yes. Thanks. I have updated it & its working.
