### ISSUE TITLE
Aniwave Is Not Working

### ISSUE THREAD

**Issue by Curiousnewbie** [jmir1/aniyomi-mpv-beta#109]
The anime extension Aniwave is not working. Its working in webview but its not accessable through the app.

! Unexpected JSON token at offset 23: Expected string literal but 'null' literal was found at path: $.result
Use 'coerceInputValues = true' in 'Json {}' builder to coerce nulls to default values.
JSON input: {"status":403,"result":null,"message":"Request is invalid.","messages":["Request is invalid."]}

This is the error shown when we try to load any anime in aniwave.

Please check it.

**Comment by kaoruwu** [comment]
Not a aniyomi but an extension problem.

!close
