### ISSUE TITLE
Sorting on the manga page affects anime page and vice versa

### ISSUE THREAD

**Issue by Mini-Sylar** [jmir1/aniyomi-mpv-beta#11]
## Problem
Idk if this is intentional but, once you choose a sort type, for instance "unread count" on manga
the anime page's sort type changes to "unseen count"
it would be nice if these two were independent from each other

## Build i'm using
I am on **preview r5144**

**Comment by jmir1** [comment]
it is intentional...

if you want it differently, i think you should use different categories that all have their own sorting mode

**Comment by jmir1** [comment]
you need to enable this setting: 
![image](https://user-images.githubusercontent.com/43830312/178163574-d7360901-65b0-4323-8f25-54fae7b53284.png)

**Comment by Mini-Sylar** [comment]
Alright, I just enabled it and created a new category for anime
everything works as I wanted
thanks!

**Comment by jmir1** [comment]
> Alright, I just enabled it and created a new category for anime everything works as I wanted thanks!

i think you can also just use the default category if you have that setting enabled.
because the default anime category and default manga category are two different things
