### ISSUE TITLE
Local anime makes the player lag a lot

### ISSUE THREAD

**Issue by MooseZM** [jmir1/aniyomi-mpv-beta#12]
I've been using this new beta and so far so good, everything works nicely. I like the new player and it seems like the perfect anime player for android since it has tracking and op skipping. But whenever i play anime i have downloaded on my phone, it starts lagging (it works fine when using regular extensions). I should also mention that i tried the very same episode on mx player and it was fine. Any fix?
Version: Aniyomi MPV Beta r5231

**Comment by jmir1** [comment]
Check the player stats (three dots in the top right corner -> toggle statistics)

If you send a screenshot of the stats, maybe I can tell you why it's lagging.

MPV is not as performant as e.g. MX player or exoplayer, in my experience.

But you can change the mpv.conf to speed up decoding.

**Comment by jmir1** [comment]
Try using this configuration:

(Paste this in `Settings -> Player -> Edit MPV configuration file`)


```
vd-lavc-fast=yes
vd-lavc-skiploopfilter=all
scale=bilinear
cscale=bilinear
dscale=bilinear
scale-antiring=0
cscale-antiring=0
dither-depth=no
correct-downscaling=no
sigmoid-upscaling=no
deband=no
hwdec=auto
```

**Comment by jmir1** [comment]
Also, can you tell me what device you are using?
Because I've only experienced dropped frames when playing 4k60fps videos.

**Comment by MooseZM** [comment]
the config you sent me made it slower for some reason. As for my phone it's a samsung A11

**Comment by jmir1** [comment]
That's weird...
Can you try playing the same file with mpv-android and see if it also drops frames?

**Comment by MooseZM** [comment]
I just tried it and it seems fine apart from a split second delay whenever I skip ahead too far. Other than that it's pretty much normal and i didn't use any configs

**Comment by MooseZM** [comment]
It seems the problem only happens in that particular anime, maybe it was encoded weirdly or something since i tried other videos with the same parameters and they worked fine
