### ISSUE TITLE
player is downloading whole video in its buffer 

### ISSUE THREAD

**Issue by himanshu8443** [jmir1/aniyomi-mpv-beta#13]
The player is downloading the whole episodes in buffer it consumed all of my data

**Comment by jmir1** [comment]
the player definitely shouldn't buffer the whole video...
the player chaches 64MB on newer android devices, 32 MB otherwise: https://github.com/jmir1/aniyomi-mpv-lib/blob/master/app/src/main/java/is/xyz/mpv/MPVView.kt#L110

**Comment by sinnghabhay80** [comment]
> The player is downloading the whole episodes in buffer it consumed all of my data

Actually what's really happening is that the progress bar and animation for same is not working for some reason.

Though it looks like buffering the episode is actually downloading and it also gets completed if you wait for an appropriate amount of time i.e. the amount of time based on your connection speed.
