### ISSUE TITLE
Crashes when you move the downloads queue 

### ISSUE THREAD

**Issue by ahmedziyaanmuhamed** [jmir1/aniyomi-mpv-beta#16]
https://user-images.githubusercontent.com/86360363/184553691-a47ab749-57ab-4123-8d4d-8f1f58f4d41e.mp4

When you re-open aniyomi it wil be stuck on the logo screen.
The only temporary fix i found out was to force stop aniyomi and clearing the cache

DEVICE DETAILS:

App version: 0.13.5.0-5231 (standard, f1169dbd9, 81, 2022-07-13T21:56Z)
Android version: 11 (SDK 30)
Android build ID: BE2029_15_220706
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlusN10
Device model: BE2029
Device product name: OnePlusN10

**Comment by ahmedziyaanmuhamed** [comment]
Btw the same thing happened on the previous 2 updates . Sorry for the late report 😅

**Comment by jmir1** [comment]
ok thanks for reporting
