### ISSUE TITLE
Optimization Request 

### ISSUE THREAD

**Issue by sinnghabhay80** [jmir1/aniyomi-mpv-beta#2]
Some icons seem way too big than tha normal version.
Like the pause/play, forward, backward in the video player, incognito mode, toggle icon, the anime, manga , etc. Category icon in the bottom. It would be more visually appealing if those are addressed and optimised for normal size like the earlier stable versions.
Thank you for your good work.

**Comment by 12ohit** [comment]
Category icons in bottom are not going to be changed and icons inside player like play/pause, forward/backward are also most likely won't be changed, the toggle icon for "incognito mode" and "download only" are now displayed by your os skin I think if I am not wrong

**Comment by sinnghabhay80** [comment]
For me I guess the request is completed as much as it could have been so I will be closing this issue request.
