### ISSUE TITLE
No extension found and other stuff 

### ISSUE THREAD

**Issue by Lukyzzz** [jmir1/aniyomi-mpv-beta#21]
I just updated and all my anime extensions just vanished, I tried to uninstall and install again but after it download and supposedly install, it still doesn't show on my list of extension and still give me tr option of "install" like I never did, can't use the extension to se animes either
Got some crashes too

**Comment by Lukyzzz** [comment]
App version: 0.14.2.0-5833 (standard, ee4ba44ad, 91, 2022-11-09T23:57Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.M625FXXS2BVJ2
Device brand: samsung
Device manufacturer: samsung
Device name: m62
Device model: SM-M625F
Device product name: m62xx

**Comment by Lukyzzz** [comment]
Now I can't install any other version of it cause it says it's downgrading, even uninstalling it

**Comment by Lukyzzz** [comment]
I'm panicking now, cause I can't install again, plz help, I'm a hopeless nobody without this app in my life, really...

**Comment by Diegopyl1209** [comment]
> I'm panicking now, cause I can't install again, plz help, I'm a hopeless nobody without this app in my life, really...
> 
> "INSTALL_FAILED_VERSION_DOWNGRADE: Package Verification Result"

make a backup -> uninstall -> install old version -> restore backup

**Comment by Diegopyl1209** [comment]
> > > I'm panicking now, cause I can't install again, plz help, I'm a hopeless nobody without this app in my life, really...
> > > "INSTALL_FAILED_VERSION_DOWNGRADE: Package Verification Result"
> > 
> > 
> > make a backup -> uninstall -> install old version -> restore backup
> 
> Can't install, I tried this, but I'm getting this error saying I'm trying to downgrade

ik, you need uninstall the app first

**Comment by Lukyzzz** [comment]
> > > > I'm panicking now, cause I can't install again, plz help, I'm a hopeless nobody without this app in my life, really...
> > > > "INSTALL_FAILED_VERSION_DOWNGRADE: Package Verification Result"
> > > 
> > > 
> > > make a backup -> uninstall -> install old version -> restore backup
> > 
> > Can't install, I tried this, but I'm getting this error saying I'm trying to downgrade
> 
> ik, you need uninstall the app first

I DON'T have the app install anymore, that's the thing and the reason why I'm panicking

**Comment by Diegopyl1209** [comment]
A
