### ISSUE TITLE
r5833

### ISSUE THREAD

**Issue by Lukyzzz** [jmir1/aniyomi-mpv-beta#22]
#21 
So, seems like r5833 was release by mistake and I install it, but after some crashes and bugs I tried to uninstall it and install the previous version, but now im getting this error  ""INSTALL_FAILED_VERSION_DOWNGRADE: Package Verification Result""
 saying I'm downgrading even tho I don't have ANY aniyomi on my phone, I can't install the r5833 either cause I don't have the APK, since I install it through the aniyomi app itself ....
 
 I'm fucked and I'm panicking, would REALLY appreciate ANY help, I'm almost addict to this app by this point, really.

**Comment by jmir1** [comment]
Did you manage to install the older version now?
I'm not sure why it says that you're downgrading if you deinstalled...

**Comment by Lukyzzz** [comment]
I searched on the internet for some time and follow a few things I find about adb or something and seems to have worked, thanks 😁

**Comment by Lukyzzz** [comment]
Btw the function of automatically download further ep while watching is sick, looking forward to it

**Comment by jmir1** [comment]
> Btw the function of automatically download further ep while watching is sick, looking forward to it

that's not implemented yet 🙈
