### ISSUE TITLE
Cover Link Broken

### ISSUE THREAD

**Issue by sinnghabhay80** [jmir1/aniyomi-mpv-beta#23]
When changing the cover for an entry it changes the cover in the details page but when in the library section it show a broken link type thing and displays no cover or doesn't changes the cover in the library section.Also some covers take unusual time while in the library section.

It is happening only for the manga section and is working fine for anime section.

**Comment by sinnghabhay80** [comment]
Ahh..., Forgot to tell you but I have also checked this in the tachiyomi app(latest build) it is working there without any problem.

**Comment by jmir1** [comment]
> Ahh..., Forgot to tell you but I have also checked this in the tachiyomi app(latest build) it is working there without any problem.

Okay, I also have this issue but I haven't yet found out why it's happening

**Comment by sinnghabhay80** [comment]
..

**Comment by jmir1** [comment]
still no updates on this.

**Comment by jmir1** [comment]
fixed in https://github.com/jmir1/aniyomi/commit/5dffac458d9fc048b0195a23ce69e3cb8cd1d69b

**Comment by sinnghabhay80** [comment]
Nice😀😀
But, Release was not pushed?

**Comment by jmir1** [comment]
not yet

**Comment by jmir1** [comment]
the update is now available.

**Comment by sinnghabhay80** [comment]
**😀😎😎**
