### ISSUE TITLE
Start Screen change option missing 

### ISSUE THREAD

**Issue by sinnghabhay80** [jmir1/aniyomi-mpv-beta#24]
When changing the bottom navigation style in general settings, when we change the options the option in the more section does get changed but the bottom navigation bar stays the same. I.e. no change

**Comment by sinnghabhay80** [comment]
Don't want to add a new issue, just informing that the default start screen option is also missing from the settings or I am not able to find it so if someone can tell me it will be appreciated.

**Comment by jmir1** [comment]
You have to restart the app for the change to take effect.

**Comment by sinnghabhay80** [comment]
> You have to restart the app for the change to take effect.

Ohh.. thanks.

Please look into the start screen option missing thing also 😀😀

**Comment by sinnghabhay80** [comment]
> Don't want to add a new issue, just informing that the default start screen option is also missing from the settings or I am not able to find it so if someone can tell me it will be appreciated.

Just wondering if there any lead.😀

**Comment by jmir1** [comment]
It was removed with Tachiyomi [v0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.14.0) in favour of app shortcuts.


> - Removed settings:
>   - Start screen (use app shortcuts in Android 7.1+ instead)

**Comment by sinnghabhay80** [comment]
Well then if that's how it is then I guess it's not negotiable.

**Comment by jmir1** [comment]
If I get more feedback asking me too as it back, I could probably still do that.
