### ISSUE TITLE
I can't access extension settings.

### ISSUE THREAD

**Issue by eokwuanga** [jmir1/aniyomi-mpv-beta#3]
When I try to access extension settings it just says "well, this is awkward" for every extension.

**Comment by jmir1** [comment]
ok , thanks for reporting the bug, i will look into it.

**Comment by jmir1** [comment]
actually, it was fixed by @Quickdev i think... you can try updating now.

**Comment by eokwuanga** [comment]
> actually, it was fixed by @Quickdesh i think... you can try updating now.

I just installed the update and it now works again like you said, thanks so much.

**Comment by jmir1** [comment]
np mate
