### ISSUE TITLE
App Statistics [Feature Request]

### ISSUE THREAD

**Issue by sinnghabhay80** [jmir1/aniyomi-mpv-beta#30]
So there's this feature in the base tachiyomi app that tells you some stats based on library etc. It would be cool if implemented here also.

Idk, probably you are already working on it, then you can probably use this issue for keeping track of😀.

**Comment by sinnghabhay80** [comment]
Sorry, a small miss from my side, this stats feature has not been included in the latest release i.e. 0.14.2.

I was actually trying to the build the app in Android studio and this saw it, they are probably working on it, or planning to release it in the near future.

Please have a look in it.😀

**Comment by jmir1** [comment]
When tachiyomi implements this, this feature will eventually be merged into aniyomi.
It just takes some time :)

**Comment by TheGoldenSun** [comment]
![08ac0310-8f8b-4f62-948e-bad73fa9d37c](https://user-images.githubusercontent.com/104534608/208241318-78cef442-0ebe-41f3-8224-4c761406e754.jpg)

@jmir1 They already have added the stats, ask arkon for further information about it they'll tell you.

**Comment by sinnghabhay80** [comment]
It's not available in the 0.14.2 build which I think is the latest.

**Comment by TheGoldenSun** [comment]
Exactly, tachiyomi users are testing it in preview. 
   


It's not available in the 0.14.2 build which I think is the latest.

**Comment by jmir1** [comment]
Alright, so this feature will definitely be in Aniyomi, I just can't tell when :)
