### ISSUE TITLE
Mis typed??

### ISSUE THREAD

**Issue by sinnghabhay80** [jmir1/aniyomi-mpv-beta#31]
In the anime history section.![Screenshot_2022-12-18-02-48-44-31_423fe07c33ed17f15a4e92e5e3a15972.jpg](https://user-images.githubusercontent.com/55084281/208266360-db6fac1f-0ac6-4d69-8970-2761df45c151.jpg) chapter -> episode and manga -> anime 

Also, I would like of this can stay open for a short while to report this kind of small details. Just feels wrong to. Create a new issue over this. One of the reasons it took me this while to report it.

**Comment by sinnghabhay80** [comment]
![Screenshot_2022-12-20-01-09-58-77_423fe07c33ed17f15a4e92e5e3a15972.jpg](https://user-images.githubusercontent.com/55084281/208507020-5335a7e9-5d14-4642-836f-d679441006b1.jpg)

manga->anime

**Comment by jmir1** [comment]
I fixed some if these mistakes in the newest update.
