### ISSUE TITLE
[App Suggestion]Merge the download and category tabs

### ISSUE THREAD

**Issue by sinnghabhay80** [jmir1/aniyomi-mpv-beta#35]
So what I mean is like merge the:
Anime and manga Download in one like it is with history and updates tab and the same with the anime category and manga category.
It would make the more organized (less cluttered?).

Also, an additional will be like removing the backup and restore from the more page as it is already present in the more->settings already.

Just a suggestion.I hope it would be helpful.

**Comment by soymadip** [comment]
> So what I mean is like merge the: Anime and manga Download in one like it is with history and updates tab and the same with the anime category and manga category. It would make the more organized (less cluttered?).

Like stable version? 
Yeah, it is way better

**Comment by sinnghabhay80** [comment]
> Like stable version?

Yup.
