### ISSUE TITLE
Lagging when opening episodes screen of a tv show with many episodes 

### ISSUE THREAD

**Issue by hvroun1** [jmir1/aniyomi-mpv-beta#38]
Whenever I open any tv show which has lots of episodes, it will hang for roughly 10 seconds every single time even though it has already downloaded the metadata.
The problem only seems to be in the beta version since the stable version doesn't hang or lag.

**Comment by hvroun1** [comment]
I noticed the fault was mine, i installed the wrong version instead of x64. Uninstalled it then re installed the correct version and worked fine.

**Comment by jmir1** [comment]
nice :+1:
