### ISSUE TITLE
[Bug Report] Downloaded file not found error.

### ISSUE THREAD

**Issue by sinnghabhay80** [jmir1/aniyomi-mpv-beta#41]
![Screenshot_2023-01-04-01-04-40-94_423fe07c33ed17f15a4e92e5e3a15972.jpg](https://user-images.githubusercontent.com/55084281/210501446-d0b4db4c-89af-490f-93db-172cabebfb5e.jpg)

Something like this.

The extension was kamyroll.

Tried others as well for now between the one I have most are broken(animepahe,Zoro, 9anime) but download was successful on gogoanime.

**Comment by sinnghabhay80** [comment]
The extension was kamyroll btw.

**Comment by jmir1** [comment]
can you try it again with the new update?

**Comment by sinnghabhay80** [comment]
Sorry for late reply, and also I will inform u as soon as I can because currently all the major extension are broke and also it was already working for gogoanime so I don't think that would be a good parameter to judge.

Also I initially got the problem on kamyroll extension and it is also broke rn so as soon as some fix is there I will update the issue here respectively.

Thanks for working in this regard.

**Comment by sinnghabhay80** [comment]
Yup I think it's fixed(atleast for me). 

Thanks.
