### ISSUE TITLE
The player keeps buffering the whole video.

### ISSUE THREAD

**Issue by LOWKI17** [jmir1/aniyomi-mpv-beta#45]
When i watch anime. The player keeps buffering the whole episode. Until it completed. Though it looks like buffering but actually its downloading the whole episode. Unlike the official version it buffer little by little. Which is good Hope it fix. When release officially.

Im using the latest mpv beta version.

**Comment by jmir1** [comment]
The player always buffers 64 megabytes in advance.
If you're streaming at a low quality, that can make up the majority of the episode.
You can change this setting in the MPV configuration with e.g. `demuxer-max-bytes=10MiB` to set the buffet size to 10 megabytes.

**Comment by LOWKI17** [comment]
Thanks author! Its working now.. Thumbs up.

**Comment by soymadip** [comment]
> The player always buffers 64 megabytes in advance. If you're streaming at a low quality, that can make up the majority of the episode. You can change this setting in the MPV configuration with e.g. `demuxer-max-bytes=10MiB` to set the buffer size to 10 megabytes.

So we can set any value here?

**Comment by jmir1** [comment]
> > The player always buffers 64 megabytes in advance. If you're streaming at a low quality, that can make up the majority of the episode. You can change this setting in the MPV configuration with e.g. `demuxer-max-bytes=10MiB` to set the buffer size to 10 megabytes.
> 
> So we can set any value here? 

Yes you can probably set anything from 1KiB to 1000GiB or more 😂

**Comment by soymadip** [comment]
> > > The player always buffers 64 megabytes in advance. If you're streaming at a low quality, that can make up the majority of the episode. You can change this setting in the MPV configuration with e.g. `demuxer-max-bytes=10MiB` to set the buffer size to 10 megabytes.
> > 
> > 
> > So we can set any value here?
> 
> Yes you can probably set anything from 1KiB to 1000GiB or more 😂

Well, when I am outside home, i gotta use cellular data, so it will help if I set it 30/40MIB😅
