### ISSUE TITLE
Error while downloading 

### ISSUE THREAD

**Issue by sinnghabhay80** [jmir1/aniyomi-mpv-beta#5]
In the new update it seems that there is a issue while downloading. It shows error - downloaded file not found while starting the download and then the download gets cancelled.

![Screenshot_2022-06-21-16-29-30-17_423fe07c33ed17f15a4e92e5e3a15972.jpg](https://user-images.githubusercontent.com/55084281/174785063-3c9c1861-afcf-423e-b054-213beddee399.jpg)

I have also tried it with multiple extensions and the problems seems to be there for every extension.

**Comment by eokwuanga** [comment]
I have this issue too, I've been using the stable version to download instead.

It started like two updates ago I think.

**Comment by jmir1** [comment]
I am actively working on fixing this.
The proper way to access files with ffmpeg varies depending on device and android versionso it is a rather complicated issue 😞

**Comment by jmir1** [comment]
should be fixed in r5057

**Comment by sinnghabhay80** [comment]
> should be fixed in r5057

I can confirm this. It's fixed in the latest build. Thanks
