### ISSUE TITLE
Bug:- Long Anime/shows(in library) takes too much time to open/load episodes ,apply filter/sorting method, update progress.

### ISSUE THREAD

**Issue by soymadip** [jmir1/aniyomi-mpv-beta#53]
Long animes like Naruto shupudden, ONE PIECE , Boruto take to much time while loading episodes. 

- Steps to reproduce:- 
1. Add long Anime like One Piece in library. 
2. Restart app
3. In anime tab, tap the anime thumbnail to open it. 
4. It will take long time to load episodes. 

- Longer the anime> longer time to load episodes.
- even if we change sorting method/ apply custom filter it takes long time to apply. 
- after watching a episode, we have to reopen the anime to update the episode progress.
- as in below Screen recording:-

https://user-images.githubusercontent.com/84225810/216532057-ce3bbebc-71e4-465b-b2bb-94504b0f817a.mp4

**Comment by soymadip** [comment]
Device:- 
App version: 0.14.2.0-5879 (standard, 45ceb2219, 93, 2023-01-14T01:30Z)
Android version: 12 (SDK 31)
Android build ID: RMX3461_11_C.06
Device brand: realme
Device manufacturer: realme
Device name: RE54BFL1
Device model: RMX3461
Device product name: RMX3461

**Comment by hvroun1** [comment]
I had the exact same problem, turns out I was using the wrong version of aniyomi (armeabiv7). Uninstalled it then I installed x64 version, worked great.

**Comment by soymadip** [comment]
> I had the exact same problem, turns out I was using the wrong version of aniyomi (armeabiv7). Uninstalled it then I installed x64 version, worked great.

It's happens even with armbiv8. 
There's a problem loading long animes.

**Comment by soymadip** [comment]
Here it is @Quickdesh

**Comment by hvroun1** [comment]
My brother, just uninstall whatever version you are using. And then install x64 version. If that still doesn't work, kindly format your phone.

**Comment by hvroun1** [comment]
My brother, just uninstall whatever version you are using. And then install x64 version. If that still doesn't work, kindly format your phone.

**Comment by jmir1** [comment]
> My brother, just uninstall whatever version you are using. And then install x64 version. If that still doesn't work, kindly format your phone.

no, this isn't a solution.
the realme RMX3461 has an armv8 processor, so installing the arm64-v8a version is the correct one, not the x86 one.

**Comment by soymadip** [comment]
> > My brother, just uninstall whatever version you are using. And then install x64 version. If that still doesn't work, kindly format your phone.
> 
> no, this isn't a solution. the realme RMX3461 has an armv8 processor, so installing the arm64-v8a version is the correct one, not the x86 one.

Yeah, i re installed many times 😮‍💨

**Comment by hvroun1** [comment]
Sorry sorry, I don't have any idea of helping you right now. All the best bro.

**Comment by soymadip** [comment]
It fixed now, 🙂
