### ISSUE TITLE
Bug:- Downloader is crashing while changing the provider order while downloading in progress. 

### ISSUE THREAD

**Issue by soymadip** [jmir1/aniyomi-mpv-beta#55]
When there are downloads from different providers, aniyomi separates them from the providers.

When download is in progress, if we change the sorting of provider, app crashes. 
- i tested with manga providers so I don't know if it happens with anime providers too. 
- [x] sample:-

https://user-images.githubusercontent.com/84225810/216635183-e148dbb7-be60-4374-ad1b-b3ac21db8732.mp4

- Crash log file:-
[aniyomi_crash_logs.txt](https://github.com/jmir1/aniyomi-mpv-beta/files/10580063/aniyomi_crash_logs.txt)

**Comment by hvroun1** [comment]
The downloader keeps failing on me. So much that I had to reinstall the stable aniyomi just to use it for downloads only.
