### ISSUE TITLE
Issue while refreshing library 

### ISSUE THREAD

**Issue by sinnghabhay80** [jmir1/aniyomi-mpv-beta#6]
When the anime library refreshes every day or so a notification occurs where it tells that new titles found in Library but all the titles are there all the time and in the new episodes section it lists every episode as well.

Though the thing only occurs in the notification as the updates page does not show such message.

**Comment by sinnghabhay80** [comment]
![Screenshot_2022-06-29-09-48-00-18_423fe07c33ed17f15a4e92e5e3a15972.jpg](https://user-images.githubusercontent.com/55084281/176350709-c7103153-e642-47f6-9f80-27069ea964da.jpg)![Screenshot_2022-06-29-09-48-13-09_423fe07c33ed17f15a4e92e5e3a15972.jpg](https://user-images.githubusercontent.com/55084281/176350754-512760ca-a670-45a5-b0b1-4a83a63fbea3.jpg)

**Comment by sinnghabhay80** [comment]
> ![Screenshot_2022-06-29-09-48-00-18_423fe07c33ed17f15a4e92e5e3a15972.jpg](https://user-images.githubusercontent.com/55084281/176350709-c7103153-e642-47f6-9f80-27069ea964da.jpg)![Screenshot_2022-06-29-09-48-13-09_423fe07c33ed17f15a4e92e5e3a15972.jpg](https://user-images.githubusercontent.com/55084281/176350754-512760ca-a670-45a5-b0b1-4a83a63fbea3.jpg)

Just for depicting what I meant.

**Comment by sinnghabhay80** [comment]
Well not sure if this was noticed. But it stands resolved in r5840.

**Comment by jmir1** [comment]
Good :)
