### ISSUE TITLE
Bug:- Player does not track watched minutes

### ISSUE THREAD

**Issue by HotCoffeMug** [jmir1/aniyomi-mpv-beta#65]
when I watch an episode the bar at the bottom remain to 0:00 and when I return to the episode list is as I never watched that episode.

**Comment by jmir1** [comment]
Can you give any more details? Cause it's not happening for me.

**Comment by HotCoffeMug** [comment]
so, I'm currently watching chainsaw man, when I open the episode the video play normally but the bar at the bottom remain at the start at 0:00, so it does not remember the position when I close the episode and continue it later.

**Comment by HotCoffeMug** [comment]
nevermind, it fixed itself
