### ISSUE TITLE
Sort By Source not working

### ISSUE THREAD

**Issue by Lukyzzz** [jmir1/aniyomi-mpv-beta#91]
It's been impossible to use some extensions that post the same chapter by multiple sources without the sort option, guess it should group all chapters by the same source but it don't
The Sort By Chapter Number and Upload Date works just fine tho
![Screenshot_20230530_120802_Aniyomi.jpg](https://github.com/jmir1/aniyomi-mpv-beta/assets/28473476/bc025ed7-937d-41dd-a3d8-b52cb9b568f0)

**Comment by jmir1** [comment]
please use the https://github.com/jmir1/aniyomi repo for issues now that the beta isn't used anymore.
